# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        reinforcement learning: 100
        imitation learning: 100
        control as inference: 100
        skill discovery: 100
        latent structure: 100
        

        Variational Inference: 50
        latent variable: 50
        latent space: 50
        robot: 50
        control: 50
        polic: 50

        representation learning: 10
        skill: 2
        option: 1
        manipulation: 1
        imitation: 1
        
# 通知の閾値
score_threshold: 100
